# Generated by Django 6.1.1 on 2026-09-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_periods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_type', models.CharField(default='FINAL', max_length=50)),
                ('duration_minutes', models.IntegerField(default=180)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='academics.unit')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='scheduling.examinationperiod')),
            ],
            options={
                'unique_together': {('period', 'unit', 'examination_type')},
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(default='SCHEDULED', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='scheduling.examination')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_capacity', models.IntegerField()),
                ('status', models.CharField(default='ALLOCATED', max_length=20)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='scheduling.examination')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_exams', to='locations.room')),
            ],
            options={
                'unique_together': {('examination', 'room')},
            },
        ),
        migrations.CreateModel(
            name='StudentExamAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, default='Pending On-Site', max_length=50, null=True)),
                ('status', models.CharField(default='ALLOCATED', max_length=20)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_allocations', to='scheduling.examination')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_seats', to='locations.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_allocations', to='academics.student')),
            ],
            options={
                'unique_together': {('examination', 'student')},
            },
        ),
    ]
