# Generated by Django 6.1.1 on 2026-09-17 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Morning Session', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['exam_date', 'start_time', 'end_time'], name='scheduling__exam_da_def604_idx'),
        ),
        migrations.AddField(
            model_name='examtimeslot',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='scheduling.examinationperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='examtimeslot',
            unique_together={('period', 'start_time', 'end_time')},
        ),
    ]
