# Generated by Django 6.1.1 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_examtimeslot_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examinationperiod',
            constraint=models.CheckConstraint(
                condition=models.Q(('start_date__lte', models.F('end_date'))),
                name='exam_period_dates_ordered',
            ),
        ),
        migrations.AddConstraint(
            model_name='examtimeslot',
            constraint=models.CheckConstraint(
                condition=models.Q(('start_time__lt', models.F('end_time'))),
                name='exam_time_slot_times_ordered',
            ),
        ),
        migrations.AddConstraint(
            model_name='examination',
            constraint=models.CheckConstraint(
                condition=models.Q(('duration_minutes__gt', 0)),
                name='examination_duration_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.CheckConstraint(
                condition=models.Q(('start_time__lt', models.F('end_time'))),
                name='exam_schedule_times_ordered',
            ),
        ),
        migrations.AddConstraint(
            model_name='examroomallocation',
            constraint=models.CheckConstraint(
                condition=models.Q(('allocated_capacity__gte', 0)),
                name='exam_room_capacity_nonnegative',
            ),
        ),
    ]
