# Generated by Django 6.1.1 on 2026-09-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='verificationcheck',
            new_name='verificatio_report__f8519f_idx',
            old_name='verification_report__4d3d69_idx',
        ),
        migrations.AddField(
            model_name='systemverificationreport',
            name='skipped_checks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='systemverificationreport',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemverificationreport',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('PASSED', 'Passed'), ('PASSED_WITH_WARNINGS', 'Passed with warnings'), ('FAILED', 'Failed')], default='RUNNING', max_length=30),
        ),
        migrations.AlterField(
            model_name='verificationcheck',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('WARNING', 'Warning'), ('SKIPPED', 'Skipped')], max_length=12),
        ),
    ]
