# Generated by Django 6.1.1 on 2026-09-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('locations', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalpracticeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('incident_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('DISMISS', 'Dismissed'), ('SANCTIONED', 'Sanctioned')], default='REPORTED', max_length=30)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_cases', to='scheduling.examination')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_malpractices', to='academics.lecturer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_cases', to='locations.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_cases', to='academics.student')),
            ],
        ),
        migrations.CreateModel(
            name='MalpracticeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='malpractice_evidence/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='malpractice.malpracticecase')),
            ],
        ),
    ]
