# Generated by Django 6.1.1 on 2026-09-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('locations', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklet_serial_number', models.CharField(help_text='Pre-printed physical booklet serial number', max_length=100, unique=True)),
                ('is_present', models.BooleanField(default=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='scheduling.examination')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to='academics.lecturer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='locations.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.student')),
            ],
            options={
                'unique_together': {('examination', 'student')},
            },
        ),
        migrations.CreateModel(
            name='InvigilatorDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='INVIGILATOR', max_length=50)),
                ('status', models.CharField(default='ASSIGNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_duties', to='scheduling.examination')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='academics.lecturer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_invigilators', to='locations.room')),
            ],
            options={
                'unique_together': {('examination', 'lecturer')},
            },
        ),
    ]
