# Generated by Django 6.1.1 on 2026-09-08 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registered', models.IntegerField(default=0)),
                ('total_attended', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('total_booklets_issued', models.IntegerField(default=0)),
                ('total_marks_uploaded', models.IntegerField(default=0)),
                ('total_anomalies', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CLEAN', 'Clean - 100% Reconciled'), ('ANOMALIES_DETECTED', 'Anomalies Detected'), ('FLAGGED_CRITICAL', 'Flagged Critical')], default='CLEAN', max_length=30)),
                ('summary', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_reports', to='scheduling.examination')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('MISSING_PHYSICAL_BOOKLET', 'Missing Physical Booklet Serial'), ('UNREGISTERED_EXAMINEE', 'Unregistered Examinee Sitting Exam'), ('UNSUBMITTED_MARKS', 'Unsubmitted Marks for Attended Candidate'), ('GHOST_MARKS', 'Ghost Marks Uploaded for Absent / Non-Attending Student'), ('DUPLICATE_BOOKLET_SERIAL', 'Duplicate Physical Booklet Serial Number'), ('UNRESOLVED_MALPRACTICE', 'Unresolved Malpractice Case Flagged'), ('OTHER_IRREGULARITY', 'Other Examination Discrepancy')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low - Minor Record Discrepancy'), ('MEDIUM', 'Medium - Discrepancy Requiring Investigation'), ('HIGH', 'High - Serious Integrity Breach'), ('CRITICAL', 'Critical - Unauthorized Examinee / Impersonation / Fraud')], default='MEDIUM', max_length=20)),
                ('description', models.TextField()),
                ('evidence_summary', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_anomalies', to='academics.student')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='academics.reconciliationreport')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursework_mark', models.DecimalField(decimal_places=2, default=0.0, help_text='Continuous Assessment Mark (out of 30/40)', max_digits=5)),
                ('exam_mark', models.DecimalField(decimal_places=2, default=0.0, help_text='Final Written Exam Mark (out of 70/60)', max_digits=5)),
                ('total_mark', models.DecimalField(decimal_places=2, default=0.0, help_text='Combined Total Score (out of 100)', max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MODERATED', 'Moderated'), ('PUBLISHED', 'Published')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='scheduling.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.student')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_marks', to='academics.lecturer')),
            ],
            options={
                'unique_together': {('student', 'examination')},
            },
        ),
    ]
