# Generated by Django 6.1.1 on 2026-09-08 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_reconciliationreport_reconciliationanomaly_and_more'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft - Mark Entry in Progress'), ('SUBMITTED', 'Submitted - Pending COD Review'), ('COD_APPROVED', 'COD Approved - Pending Dean Review'), ('COD_REJECTED', 'COD Rejected - Returned to Lecturer'), ('DEAN_APPROVED', 'Dean Approved - Pending Final Review'), ('DEAN_REJECTED', 'Dean Rejected - Returned to Lecturer/COD'), ('PUBLISHED', 'Published - Results Released to Students'), ('FINAL_REJECTED', 'Exam Authority Rejected - Returned for Correction')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('dean_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cod_reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('dean_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_submissions', to='academics.department')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_submissions', to='scheduling.examination')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_submissions', to='academics.lecturer')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_submissions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_submissions', to='academics.school')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_submissions', to='academics.unit')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('examination', 'lecturer')},
            },
        ),
        migrations.AddField(
            model_name='studentmark',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_marks', to='academics.resultsubmission'),
        ),
        migrations.CreateModel(
            name='ResultWorkflowAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='academics.resultsubmission')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
