# Generated by Django 6.1.1 on 2026-09-09 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_resultsubmission_studentmark_submission_and_more'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('threshold_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Configurable rule threshold (e.g., 75.00 for attendance %)', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(choices=[('ELIGIBLE', 'Eligible (Overridden)'), ('CONDITIONALLY_ELIGIBLE', 'Conditionally Eligible'), ('NOT_ELIGIBLE', 'Not Eligible / Revoked')], max_length=30)),
                ('reason', models.TextField(help_text='Mandatory audit justification for the override')),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_eligibility_overrides', to=settings.AUTH_USER_MODEL)),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_overrides', to='scheduling.examination')),
                ('examination_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_overrides', to='scheduling.examinationperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_overrides', to='academics.student')),
            ],
            options={
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('TIMETABLE_PUBLISHED', 'Timetable Published'), ('TIMETABLE_CHANGE', 'Timetable Schedule Change'), ('ELIGIBILITY_UPDATE', 'Examination Eligibility Update'), ('EXAM_PASS_READY', 'Examination Pass Available'), ('DUTY_REMINDER', 'Upcoming Invigilation Duty Reminder'), ('DUTY_ASSIGNED', 'New Invigilation Duty Assigned'), ('RESULTS_PUBLISHED', 'Examination Results Published'), ('RESULTS_SUBMITTED', 'Results Awaiting Review'), ('RESULTS_REJECTED', 'Results Rejected / Returned'), ('MALPRACTICE_FLAGGED', 'Malpractice Case Update'), ('ADMIN_ALERT', 'Administrative Alert')], max_length=50)),
                ('related_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('dedup_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='academics.notification')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('CONDITIONALLY_ELIGIBLE', 'Conditionally Eligible'), ('PENDING_CLEARANCE', 'Pending Clearance'), ('NOT_ELIGIBLE', 'Not Eligible')], default='PENDING_CLEARANCE', max_length=30)),
                ('is_eligible', models.BooleanField(default=False)),
                ('rules_passed', models.IntegerField(default=0)),
                ('rules_failed', models.IntegerField(default=0)),
                ('evaluation_details', models.JSONField(default=dict)),
                ('has_active_override', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('examination_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_evaluations', to='scheduling.examinationperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_evaluations', to='academics.student')),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'unique_together': {('student', 'examination_period')},
            },
        ),
        migrations.CreateModel(
            name='StudentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.IntegerField(default=1)),
                ('clearance_type', models.CharField(choices=[('FINANCIAL', 'Financial / Fee Clearance'), ('ADMINISTRATIVE', 'Administrative Clearance'), ('DISCIPLINARY', 'Disciplinary Clearance'), ('ATTENDANCE', 'Lecture Attendance Clearance')], max_length=30)),
                ('status', models.CharField(choices=[('CLEARED', 'Cleared'), ('PENDING', 'Pending Clearance'), ('NOT_CLEARED', 'Not Cleared / Blocked'), ('EXEMPTED', 'Exempted')], default='CLEARED', max_length=20)),
                ('source_system', models.CharField(default='MANUAL', max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_clearances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='academics.student')),
            ],
            options={
                'ordering': ['student', 'clearance_type'],
                'unique_together': {('student', 'academic_year', 'semester', 'clearance_type')},
            },
        ),
    ]
